// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MadPlanner.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Models.Ingrediens", b =>
                {
                    b.Property<int>("RetId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("ProduktId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("Grams")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("RetId", "ProduktId");

                    b.HasIndex("ProduktId");

                    b.ToTable("Ingredienser");
                });

            modelBuilder.Entity("Models.Madplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Madplaner");
                });

            modelBuilder.Entity("Models.MadplanRet", b =>
                {
                    b.Property<int>("MadplanId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int?>("RetId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("MadplanId", "RetId");

                    b.HasIndex("RetId");

                    b.ToTable("MadplanRetter");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int?>("Butik")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<int>("Grams")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("PackingType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnOrder(4);

                    b.Property<string>("SeedKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Varenummer")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.ToTable("Produkter");
                });

            modelBuilder.Entity("Models.Ret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL")
                        .HasColumnOrder(10);

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<bool>("Leftovers")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<bool>("PorkBased")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<double?>("Price")
                        .HasColumnType("REAL")
                        .HasColumnOrder(9);

                    b.Property<string>("SeedKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Takeaway")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<bool>("Vegetarian")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("Retter");
                });

            modelBuilder.Entity("Models.Ingrediens", b =>
                {
                    b.HasOne("Models.Produkt", "Produkt")
                        .WithMany("Ingredienser")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Ret", "Ret")
                        .WithMany("Ingredienser")
                        .HasForeignKey("RetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produkt");

                    b.Navigation("Ret");
                });

            modelBuilder.Entity("Models.MadplanRet", b =>
                {
                    b.HasOne("Models.Madplan", "Madplan")
                        .WithMany("MadplanRetter")
                        .HasForeignKey("MadplanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Ret", "Ret")
                        .WithMany("MadplanRetter")
                        .HasForeignKey("RetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Madplan");

                    b.Navigation("Ret");
                });

            modelBuilder.Entity("Models.Madplan", b =>
                {
                    b.Navigation("MadplanRetter");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Navigation("Ingredienser");
                });

            modelBuilder.Entity("Models.Ret", b =>
                {
                    b.Navigation("Ingredienser");

                    b.Navigation("MadplanRetter");
                });
#pragma warning restore 612, 618
        }
    }
}
