using Models;

namespace Seeders;

public class ProduktSeeder : ISeeder<Produkt>
{
    public List<Produkt> Seed()
    {
        // Ingefær
        // Hvidløg

        return new List<Produkt> {
            new Produkt {
                Name = "Blåbær Æble Grød",
                Note = "Baby grød / mos",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 120,
                Calories = 95,
                Butik = Butik.Rema1000,
                Varenummer = 160227,
            },
            new Produkt {
                Name = "Æble Hindbær Grød",
                Note = "Baby grød / mos",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 120,
                Calories = 95,
                Butik = Butik.Rema1000,
                Varenummer = 160264,
            },
            new Produkt {
                Name = "Jordbær Banan Grød",
                Note = "Baby grød / mos",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 120,
                Calories = 95,
                Butik = Butik.Rema1000,
                Varenummer = 160228,
            },
            new Produkt {
                Name = "Pære Mango Grød",
                Note = "Baby grød / mos",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 120,
                Calories = 95,
                Butik = Butik.Rema1000,
                Varenummer = 160187,
            },
            new Produkt {
                Name = "Fersken Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160283,
            },
            new Produkt {
                Name = "Banan Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160238,
            },
            new Produkt {
                Name = "Smoothie med havre",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160256,
            },
            new Produkt {
                Name = "Blåbær Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160140,
            },
            new Produkt {
                Name = "Gulerod Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160143,
            },
            new Produkt {
                Name = "Sveske Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160254,
            },
            new Produkt {
                Name = "Æble Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160113,
            },
            new Produkt {
                Name = "Mango Smoothie",
                Note = "Baby mos til grød",
                PackingType = PackingType.Pose,
                Price = 6.00,
                Grams = 90,
                Calories = 64,
                Butik = Butik.Rema1000,
                Varenummer = 160114,
            },
            new Produkt {
                Name = "Champignon",
                Note = "Økologisk champignon skiveskåret",
                PackingType = PackingType.Pose,
                Price = 7.00,
                Grams = 100,
                Calories = 22,
                Butik = Butik.Rema1000,
                Varenummer = 306703,
                SeedKey = "champignon"
            },
            new Produkt {
                Name = "Grillpølser",
                Note = "Rema pølser",
                PackingType = PackingType.Pose,
                Price = 29.95,
                Grams = 500,
                Calories = 252,
                Butik = Butik.Rema1000,
                Varenummer = 410961,
                SeedKey = "polse"
            },
            new Produkt {
                Name = "Cafe creme bønner",
                Note = "Kaffe bønner",
                PackingType = PackingType.Pose,
                Price = 99.00,
                Grams = 1000,
                Calories = 1,
                Butik = Butik.Rema1000,
                Varenummer = 50418,
            },
            new Produkt {
                Name = "Arabica bønner",
                Note = "Kaffe bønner",
                PackingType = PackingType.Pose,
                Price = 35.95,
                Grams = 400,
                Calories = 1,
                Butik = Butik.Rema1000,
                Varenummer = 50250,
            },
            new Produkt {
                Name = "Arabica bønner",
                Note = "Økologiske Kaffe bønner",
                PackingType = PackingType.Pose,
                Price = 39.95,
                Grams = 400,
                Calories = 1,
                Butik = Butik.Rema1000,
                Varenummer = 50543,
            },
            new Produkt {
                Name = "Sojabønner",
                Note = "Edermame bønner fra frost",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 250,
                Calories = 130,
                Butik = Butik.Rema1000,
                Varenummer = 40798,
                SeedKey = "edermame"
            },
            new Produkt {
                Name = "Vanilje Skyr",
                Note = "Cheasy skyr 0,2%",
                PackingType = PackingType.Pakke,
                Price = 29.95,
                Grams = 1000,
                Calories = 59,
                Butik = Butik.Rema1000,
                Varenummer = 24015,
            },
            new Produkt {
                Name = "Mango & Lime Skyr",
                Note = "Cheasy skyr 0,2%",
                PackingType = PackingType.Pakke,
                Price = 29.95,
                Grams = 1000,
                Calories = 59,
                Butik = Butik.Rema1000,
                Varenummer = 24017,
            },
            new Produkt {
                Name = "Skyr",
                Note = "Kløver naturel skyr 0,2%",
                PackingType = PackingType.Pakke,
                Price = 22.95,
                Grams = 1000,
                Calories = 65,
                Butik = Butik.Rema1000,
                Varenummer = 20400,
            },
            new Produkt {
                Name = "Cremefraiche",
                Note = "9%",
                PackingType = PackingType.Enhed,
                Price = 14.95,
                Grams = 500,
                Calories = 110,
                Butik = Butik.Rema1000,
                Varenummer = 21930,
            },
            new Produkt {
                Name = "Cremefraiche",
                Note = "Karolines køkken 18%",
                PackingType = PackingType.Enhed,
                Price = 10.75,
                Grams = 250,
                Calories = 186,
                Butik = Butik.Rema1000,
                Varenummer = 23418,
            },
            new Produkt {
                Name = "Bladselleri",
                Note = "Økologisk bladselleri",
                PackingType = PackingType.Pose,
                Price = 15.00,
                Grams = 400,
                Calories = 23,
                Butik = Butik.Rema1000,
                Varenummer = 306742,
            },
            new Produkt {
                Name = "Rødvinssauce",
                Note = "Karolines rødvinssovs",
                PackingType = PackingType.Pakke,
                Price = 17.95,
                Grams = 500,
                Calories = 67,
                Butik = Butik.Rema1000,
                Varenummer = 29225,
            },
            new Produkt {
                Name = "Skinke strimler",
                Note = "Kogt skinke i strimler (tern). Pakke af 2",
                PackingType = PackingType.Pakke,
                Price = 16.95,
                Grams = 200,
                Calories = 106,
                Butik = Butik.Rema1000,
                Varenummer = 412010,
                SeedKey = "skinke-strimler"
            },
            new Produkt {
                Name = "Revet ost",
                Note = "Karolines køkken - mozzarella",
                PackingType = PackingType.Pose,
                Price = 17.95,
                Grams = 200,
                Calories = 260,
                Butik = Butik.Rema1000,
                Varenummer = 455522,
            },
            new Produkt {
                Name = "Revet ost",
                Note = "Økologisk revet mozzarella",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 140,
                Calories = 290,
                Butik = Butik.Rema1000,
                Varenummer = 455506,
                SeedKey = "revet-ost"
            },
            new Produkt {
                Name = "Revet ost",
                Note = "Pizzatopping",
                PackingType = PackingType.Pose,
                Price = 17.95,
                Grams = 200,
                Calories = 291,
                Butik = Butik.Rema1000,
                Varenummer = 455520,
            },
            new Produkt {
                Name = "Grov tærtedej",
                PackingType = PackingType.Stk,
                Price = 11.95,
                Grams = 275,
                Calories = 345,
                Butik = Butik.Rema1000,
                Varenummer = 412387,
                SeedKey = "taertedej"
            },
            new Produkt {
                Name = "Hytteost",
                Note = "Cheasy 1,5%",
                PackingType = PackingType.Pakke,
                Price = 14.5,
                Grams = 250,
                Calories = 69,
                Butik = Butik.Rema1000,
                Varenummer = 28827,
                SeedKey = "hytteost"
            },
            new Produkt {
                Name = "Samosa",
                Note = "2 stk. fra Ana",
                PackingType = PackingType.Pose,
                Price = 35,
                Grams = 1, // TODO
                Calories = 1, // TODO
                Butik = Butik.Ana,
                SeedKey = "samosa"
            },
            new Produkt {
                Name = "Stor salat",
                Note = "Blandet salat fra Ana",
                PackingType = PackingType.Enhed,
                Price = 48,
                Grams = 1, // TODO
                Calories = 1, // TODO
                Butik = Butik.Ana,
                SeedKey = "stor-salat"
            },
            new Produkt {
                Name = "Lille salat",
                Note = "Blandet salat fra Ana",
                PackingType = PackingType.Enhed,
                Price = 38,
                Grams = 1, // TODO
                Calories = 1, // TODO
                Butik = Butik.Ana,
                SeedKey = "lille-salat"
            },
            new Produkt {
                Name = "Solsikkerugbrød",
                Note = "",
                PackingType = PackingType.Pose,
                Price = 25.5,
                Grams = 950,
                Calories = 234,
                Butik = Butik.Rema1000,
                Varenummer = 61508,
            },
            new Produkt {
                Name = "Blåbær",
                Note = "Frosne blåbær",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 250,
                Calories = 69,
                Butik = Butik.Rema1000,
                Varenummer = 40825,
            },
            new Produkt {
                Name = "Ricotta",
                Note = "Ambrosi",
                PackingType = PackingType.Pakke,
                Price = 10.5,
                Grams = 250,
                Calories = 97,
                Butik = Butik.Rema1000,
                Varenummer = 451619,
            },
            new Produkt {
                Name = "Hakkede tomater",
                Note = "Med basilikum og oregano",
                PackingType = PackingType.Dåse,
                Price = 7.5,
                Grams = 400,
                Calories = 24,
                Butik = Butik.Rema1000,
                Varenummer = 108334,
                SeedKey = "hakkede-tomater"
            },
            new Produkt {
                Name = "Kidney bønner i chilisauce",
                PackingType = PackingType.Dåse,
                Price = 7.95,
                Grams = 410,
                Calories = 100,
                Butik = Butik.Rema1000,
                Varenummer = 107912,
            },
            new Produkt {
                Name = "Kikærter Økologisk",
                PackingType = PackingType.Dåse,
                Price = 7.5,
                Grams = 400,
                Calories = 117,
                Butik = Butik.Rema1000,
                Varenummer = 100042,
            },
            new Produkt {
                Name = "Tomat Pasta",
                Note = "Tomat Purre",
                PackingType = PackingType.Dåse,
                Price = 4.95,
                Grams = 140,
                Calories = 86,
                Butik = Butik.Rema1000,
                Varenummer = 111408,
                SeedKey = "tomat-purre"
            },
            new Produkt {
                Name = "Kokosmælk",
                PackingType = PackingType.Dåse,
                Price = 7.75,
                Grams = 400,
                Calories = 162,
                Butik = Butik.Rema1000,
                Varenummer = 120171,
                SeedKey = "kokos"
            },
            new Produkt {
                Name = "Majs",
                PackingType = PackingType.Dåse,
                Price = 7.50,
                Grams = 300,
                Calories = 79,
                Butik = Butik.Rema1000,
                Varenummer = 100425,
            },
            new Produkt {
                Name = "Aspargessnitter",
                PackingType = PackingType.Dåse,
                Price = 12.95,
                Grams = 430,
                Calories = 11,
                Butik = Butik.Rema1000,
                Varenummer = 100166,
            },
            new Produkt {
                Name = "Salsa Medium",
                Note = "Tex Mex Salsasauce Medium",
                PackingType = PackingType.Glas,
                Price = 9.75,
                Grams = 315,
                Calories = 53,
                Butik = Butik.Rema1000,
                Varenummer = 102810,
            },
            new Produkt {
                Name = "Tortillas",
                Note = "Tex Mex Fuldkorns Tortillas",
                PackingType = PackingType.Pose,
                Price = 12.25,
                Grams = 370,
                Calories = 299,
                Butik = Butik.Rema1000,
                Varenummer = 102831,
            },
            new Produkt {
                Name = "Rød Karrypasta",
                PackingType = PackingType.Glas,
                Price = 10.95,
                Grams = 110,
                Calories = 222,
                Butik = Butik.Rema1000,
                Varenummer = 100831,
            },
            new Produkt {
                Name = "Ris",
                Note = "Jasmin ris",
                PackingType = PackingType.Pose,
                Price = 14.95,
                Grams = 1000,
                Calories = 357,
                Butik = Butik.Rema1000,
                Varenummer = 98164,
                SeedKey = "ris"
            },
            new Produkt {
                Name = "Pasta",
                Note = "Fusilli Fuldkorn Økologisk",
                PackingType = PackingType.Pose,
                Price = 11.95,
                Grams = 500,
                Calories = 350,
                Butik = Butik.Rema1000,
                Varenummer = 90330,
                SeedKey = "fusilli"
            },
            new Produkt {
                Name = "Suppehorn",
                Note = "Pasta horn",
                PackingType = PackingType.Pose,
                Price = 9.5,
                Grams = 500,
                Calories = 347,
                Butik = Butik.Rema1000,
                SeedKey = "suppehorn",
                Varenummer = 90814,
            },
            new Produkt {
                Name = "Spaghetti",
                Note = "Økologisk Fuldkorns Spaghetti Pasta",
                PackingType = PackingType.Pose,
                Price = 8.95,
                Grams = 500,
                Calories = 350,
                Butik = Butik.Rema1000,
                Varenummer = 90335,
            },
            new Produkt {
                Name = "Tortiglioni",
                Note = "De Cecco - gode pasta",
                PackingType = PackingType.Pose,
                Price = 21.5,
                Grams = 500,
                Calories = 351,
                Butik = Butik.Lovbjerg
            },
            new Produkt {
                Name = "Tortellini",
                Note = "Ricotta og spinat (TODO tjek kcal og pris)",
                PackingType = PackingType.Karton,
                Price = 24.95,
                Grams = 500,
                Calories = 400,
                Butik = Butik.Coop365
            },
            new Produkt {
                Name = "Lasagneplader",
                Note = "Fuldkorns lasagneplader",
                PackingType = PackingType.Pakke,
                Price = 16.95,
                Grams = 500,
                Calories = 338,
                Butik = Butik.Rema1000,
                Varenummer = 90348,
                SeedKey = "lasagne-plader"
            },
            new Produkt {
                Name = "Bucatini",
                Note = "Makaroni Pasta",
                PackingType = PackingType.Pose,
                Price = 9.95,
                Grams = 500,
                Calories = 347,
                Butik = Butik.Rema1000,
                Varenummer = 90363,
            },
            new Produkt {
                Name = "Mornaysauce",
                Note = "Bechamel / oste sauce",
                PackingType = PackingType.Karton,
                Price = 17.95,
                Grams = 500,
                Calories = 140,
                Butik = Butik.Rema1000,
                Varenummer = 29210,
                SeedKey = "bechamel"
            },
            new Produkt {
                Name = "Tomatsuppe",
                Note = "Karolines Køkken Tomatsuppe",
                PackingType = PackingType.Karton,
                Price = 30.95,
                Grams = 1000,
                Calories = 50,
                Butik = Butik.Rema1000,
                Varenummer = 29253,
                SeedKey = "karoline-tomat"
            },
            new Produkt {
                Name = "Pitabrød",
                Note = "Fuldkorns pitabrød (TODO tjek kcal)",
                PackingType = PackingType.Pose,
                Price = 5.95,
                Grams = 320,
                Calories = 237,
                Butik = Butik.Rema1000,
                SeedKey = "pita"
            },
            new Produkt {
                Name = "Røde Linser",
                Note = "Røde Split Linser",
                PackingType = PackingType.Pose,
                Price = 16.95,
                Grams = 400,
                Calories = 346,
                Butik = Butik.Rema1000,
                Varenummer = 91398,
            },
            new Produkt {
                Name = "Tartelet skaller",
                Note = "Humlum Luxus tarteletter",
                PackingType = PackingType.Pose,
                Price = 14.75,
                Grams = 225,
                Calories = 570,
                Butik = Butik.Rema1000,
                Varenummer = 73011,
            },
            new Produkt {
                Name = "Burgerboller",
                Note = "Fuldkorns burgerboller",
                PackingType = PackingType.Pose,
                Price = 20.5,
                Grams = 320,
                Calories = 260,
                Butik = Butik.Rema1000,
                Varenummer = 66035,
            },
            new Produkt {
                Name = "Nudler",
                Note = "Egg noodles",
                PackingType = PackingType.Pose,
                Price = 6.95,
                Grams = 250,
                Calories = 364,
                Butik = Butik.Rema1000,
                Varenummer = 96652,
            },
            new Produkt {
                Name = "Falafel",
                Note = "Urtekram falafler",
                PackingType = PackingType.Pose,
                Price = 59.95,
                Grams = 500,
                Calories = 321,
                Butik = Butik.Lovbjerg
            },
            new Produkt {
                Name = "Wok blanding",
                Note = "Wok blanding fra frost",
                PackingType = PackingType.Pose,
                Price = 13.95,
                Grams = 400,
                Calories = 37,
                Butik = Butik.Rema1000,
                Varenummer = 40768,
                SeedKey = "wok-blanding"
            },
            new Produkt {
                Name = "Blomkålsris",
                Note = "Økologiske Blomkålsris fra frost",
                PackingType = PackingType.Pose,
                Price = 13.95,
                Grams = 350,
                Calories = 28,
                Butik = Butik.Rema1000,
                Varenummer = 40840,
            },
            new Produkt {
                Name = "Hakket oksekød",
                Note = "8%-12%",
                PackingType = PackingType.Pakke,
                Price = 44.95,
                Grams = 500,
                Calories = 172,
                Butik = Butik.Rema1000,
                Varenummer = 400171,
                SeedKey = "hakket-okse"
            },
            new Produkt {
                Name = "Hakket grisekød",
                Note = "8%-12%",
                PackingType = PackingType.Pakke,
                Price = 36.95,
                Grams = 400,
                Calories = 168,
                Butik = Butik.Rema1000,
                Varenummer = 401001,
            },
            new Produkt {
                Name = "Hakket kyllingekød",
                Note = "7%-10%",
                PackingType = PackingType.Pakke,
                Price = 34.95,
                Grams = 400,
                Calories = 155,
                Butik = Butik.Rema1000,
                Varenummer = 404899,
            },
            new Produkt {
                Name = "Kyllingebrystfilet",
                Note = "Karolines Madlavningsfløde 8%",
                PackingType = PackingType.Pakke,
                Price = 34.95,
                Grams = 280,
                Calories = 95,
                Butik = Butik.Rema1000,
                Varenummer = 404997,
            },
            new Produkt {
                Name = "Madlavningsfløde",
                Note = "Karolines Madlavningsfløde 8%",
                PackingType = PackingType.Karton,
                Price = 12.75,
                Grams = 250,
                Calories = 115,
                Butik = Butik.Rema1000,
                Varenummer = 21878,
            },
            new Produkt {
                Name = "Pizzabund",
                Note = "Surdejs pizzabund",
                PackingType = PackingType.Pose,
                Price = 19.95,
                Grams = 200,
                Calories = 249,
                Butik = Butik.Netto
            },
            new Produkt {
                Name = "Mascarpone",
                PackingType = PackingType.Pakke,
                Price = 19.95,
                Grams = 250,
                Calories = 411,
                Butik = Butik.Rema1000,
                Varenummer = 24197,
            },
            new Produkt {
                Name = "Mozarella",
                Note = "Mozarella ost i blok",
                PackingType = PackingType.Pose,
                Price = 8.5,
                Grams = 125,
                Calories = 251,
                Butik = Butik.Rema1000,
                Varenummer = 452016,
                SeedKey = "mozarella-blok"
            },
            new Produkt {
                Name = "Grana Padano",
                Note = "Paramsan ost i blok",
                PackingType = PackingType.Pakke,
                Price = 33.95,
                Grams = 200,
                Calories = 398,
                Butik = Butik.Rema1000,
                Varenummer = 455418,
            },
            new Produkt {
                Name = "Serano skinke",
                Note = "Hola! Spansk Serano",
                PackingType = PackingType.Pakke,
                Price = 12.95,
                Grams = 60,
                Calories = 232,
                Butik = Butik.Rema1000,
                Varenummer = 411307,
                SeedKey = "serano"
            },
            new Produkt {
                Name = "Æg",
                Note = "Skrabeæg 10 stk",
                PackingType = PackingType.Pakke,
                Price = 24.85,
                Grams = 350,
                Calories = 141,
                Butik = Butik.Rema1000,
                Varenummer = 224233,
                SeedKey = "egg"
            },
            new Produkt {
                Name = "Salciccia",
                Note = "Italiensk pølse",
                PackingType = PackingType.Pakke,
                Price = 49.95,
                Grams = 200,
                Calories = 258,
                Butik = Butik.Lovbjerg
            },
            new Produkt {
                Name = "Minimælk",
                Note = "0,4% Fedt",
                PackingType = PackingType.Karton,
                Price = 10.95,
                Grams = 1000,
                Calories = 36,
                Butik = Butik.Rema1000,
                Varenummer = 21464,
                SeedKey = "milk"
            },
            new Produkt {
                Name = "Pesto",
                Note = "Rød Pesto",
                PackingType = PackingType.Glas,
                Price = 6.80,
                Grams = 130,
                Calories = 410,
                Butik = Butik.Rema1000,
                Varenummer = 108648,
            },
            new Produkt {
                Name = "Pesto",
                Note = "Grøn Pesto",
                PackingType = PackingType.Glas,
                Price = 6.80,
                Grams = 130,
                Calories = 410,
                Butik = Butik.Rema1000,
                Varenummer = 108649,
                SeedKey = "billig-pesto"
            },
            new Produkt {
                Name = "Pesto",
                Note = "Grøn Pesto med Basilikum (den gode)",
                PackingType = PackingType.Pakke,
                Price = 16.95,
                Grams = 130,
                Calories = 497,
                Butik = Butik.Rema1000,
                Varenummer = 413313,
            },
            new Produkt {
                Name = "Løg",
                Note = "Økologisk",
                PackingType = PackingType.Pose,
                Price = 11.00,
                Grams = 750,
                Calories = 40,
                Butik = Butik.Rema1000,
                Varenummer = 306967,
                SeedKey = "log",
            },
            new Produkt {
                Name = "Rødløg",
                Note = "Økologisk",
                PackingType = PackingType.Pose,
                Price = 12.00,
                Grams = 500,
                Calories = 44,
                Butik = Butik.Rema1000,
                Varenummer = 306954,
            },
            new Produkt {
                Name = "Gulerødder",
                Note = "Økologisk",
                PackingType = PackingType.Pose,
                Price = 14.00,
                Grams = 1000,
                Calories = 41,
                Butik = Butik.Rema1000,
                Varenummer = 306570,
                SeedKey = "gulerodder"
            },
            new Produkt {
                Name = "Kartofler",
                Note = "Økologisk",
                PackingType = PackingType.Pose,
                Price = 12.00,
                Grams = 1000,
                Calories = 82,
                Butik = Butik.Rema1000,
                Varenummer = 306928,
                SeedKey = "kartofel"
            },
            new Produkt {
                Name = "Spidskål",
                Note = "Økologisk",
                PackingType = PackingType.Stk,
                Price = 16.00,
                Grams = 1000,
                Calories = 27,
                Butik = Butik.Rema1000,
                Varenummer = 306618,
                SeedKey = "spidskaal"
            },
            new Produkt {
                Name = "Agurk",
                Note = "Økologisk",
                PackingType = PackingType.Stk,
                Price = 9.00,
                Grams = 300,
                Calories = 11,
                Butik = Butik.Rema1000,
                Varenummer = 306076,
                SeedKey = "agurk"
            },
            new Produkt {
                Name = "Tomater",
                Note = "Økologisk",
                PackingType = PackingType.Pakke,
                Price = 19.00,
                Grams = 400,
                Calories = 20,
                Butik = Butik.Rema1000,
                Varenummer = 306175,
                SeedKey = "tomater"
            },
            new Produkt {
                Name = "Avocado",
                Note = "Modne Avocadoer - Guacamole",
                PackingType = PackingType.Pakke,
                Price = 16.50,
                Grams = 300,
                Calories = 160,
                Butik = Butik.Rema1000,
                Varenummer = 305415,
            },
            new Produkt {
                Name = "Spinat",
                Note = "Frisk baby spinat",
                PackingType = PackingType.Pose,
                Price = 12.00,
                Grams = 75,
                Calories = 23,
                Butik = Butik.Rema1000,
                Varenummer = 306423,
                SeedKey = "spinat"
            },
        };
    }
}
